
INSERT INTO injury_general (injury_id, injury_name, injury_sport, body_part, pain_location, 
	swelling, bruising, instability, limited_range_of_motion, audible_pop) VALUES
(1,  'Ankle Sprain', 'Basketball', 'Ankle', 'Around the ankle joint, most often lateral (outside)', 'Yes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(2,  'ACL Tear', 'Basketball', 'Knee', 'Deep in the knee, sometimes diffuse', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
(3,  'Meniscus Tear', 'Basketball', 'Knee', 'Joint line of the knee (inner or outer)', 'Yes', 'No', 'Yes', 'Yes', 'Sometimes'),
(4,  'Patellar Tendinitis - Jumper''s Knee', 'Basketball', 'Knee', 'Just below the kneecap, at the patellar tendon', 'No', 'No', 'No', 'Yes', 'No'),
(5,  'Achilles Tendon Rupture', 'Basketball', 'Lower Calf', 'Back of the ankle/lower calf', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
(6,  'Finger Sprain', 'Basketball', 'Finger Joint', 'Localized to the affected finger joint', 'Yes', 'Yes', 'No', 'Yes', 'No'),
(7,  'Finger Fracture', 'Basketball', 'Finger Joint', 'Localized to the affected finger joint', 'Yes', 'Yes', 'Sometimes', 'Yes', 'No'),
(8,  'Hamstring Strain', 'Basketball', 'Hamstring', 'Back of the thigh, sudden and sharp mid-sprint', 'Sometimes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(9,  'Lower Back Strain', 'Basketball', 'Lower Back', 'Lower b ack, sometimes radiating to hip', 'No', 'No', 'No', 'Yes', 'No'),
(10, 'Concussion', 'Basketball', 'Head', 'Head/neck, may include headache', 'Sometimes', 'Sometimes', 'Yes', 'No', 'No'),
(11, 'Wrist Sprain', 'Basketball', 'Wrist', 'Localized to the wrist, sometimes radiating into the hand', 'Yes', 'Yes', 'No', 'Yes', 'No'),
(12, 'Wrist Fracture', 'Basketball', 'Wrist', 'Localized to the wrist, sometimes radiating into the hand', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(13, 'Rotator Cuff Strain', 'Baseball', 'Shoulder', 'Front/side of shoulder, may radiate down arm', 'No', 'No', 'No', 'Yes', 'No'),
(14, 'Rotator Cuff Tear', 'Baseball', 'Shoulder', 'Front/side of shoulder, may radiate down arm', 'No', 'Sometimes', 'Yes', 'Yes', 'No'),
(15, 'UCL Sprain', 'Baseball', 'Elbow', 'Inner (medial) elbow', 'No', 'No', 'Yes', 'No', 'No'),
(16, 'UCL Tear', 'Baseball', 'Elbow', 'Inner (medial) elbow', 'No', 'Sometimes', 'Yes', 'No', 'Yes'),
(17, 'Labral Tear - Shoulder', 'Baseball', 'Shoulder', 'Deep in shoulder joint, catching sensation', 'No', 'No', 'Yes', 'Yes', 'Sometimes'),
(18, 'Oblique Strain', 'Baseball', 'Torso', 'Side of torso/ribcage, sharp and localized', 'No', 'Sometimes', 'No', 'Yes', 'No'),
(19, 'Hamstring Strain', 'Baseball', 'Hamstring', 'Back of thigh, sudden/sharp mid-sprint', 'Sometimes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(20, 'Ankle Sprain', 'Baseball', 'Ankle', 'Around ankle joint, lateral side most common', 'Yes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(21, 'Concussion', 'Baseball', 'Head', 'Head/neck, possible headache', 'Sometimes', 'Sometimes', 'Yes', 'No', 'No'),
(22, 'Hand Contusion', 'Baseball', 'Hand', 'Localized to impact point', 'Yes', 'Yes', 'No', 'Yes', 'No'),
(23, 'Wrist Fracture', 'Baseball', 'Wrist', 'Localized to impact point', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(24, 'Knee Injury - Meniscus', 'Baseball', 'Knee', 'Around/behind kneecap, or joint line', 'Yes', 'No', 'Yes', 'Yes', 'Sometimes'),
(25, 'Knee Injury - Patellar', 'Baseball', 'Knee', 'Around/behind kneecap, or joint line', 'Yes', 'No', 'No', 'Yes', 'No'),
(26, 'Lower Back Strain / Spondylolysis', 'Baseball', 'Lower Back', 'Lower back, may radiate to hip/buttock', 'No', 'No', 'No', 'Yes', 'No'),
(27, 'ACL Tear', 'Football', 'Knee', 'Deep in the knee joint', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
(28, 'Concussion', 'Football', 'Head', 'Generalized headache or pressure in the head', 'No', 'No', 'Yes', 'No', 'No'),
(29, 'Ankle Sprain', 'Football', 'Ankle', 'Above the ankle joint, between the tibia and fibula', 'Yes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(30, 'Hamstring Strain', 'Football', 'Hamstring', 'Back of the thigh', 'Sometimes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(31, 'MCL Sprain', 'Football', 'Knee', 'Inner side of knee', 'Yes', 'Sometimes', 'Yes', 'Yes', 'Sometimes'),
(32, 'Shoulder Dislocation', 'Football', 'Shoulder', 'Outer shoulder/deltoid area', 'Yes', 'No', 'Yes', 'Yes', 'Yes'),
(33, 'Turf Toe', 'Football', 'Big Toe', 'Base of big toe', 'Yes', 'Sometimes', 'Yes', 'Yes', 'Sometimes'),
(34, 'Achilles Tear', 'Football', 'Achilles Tendon', 'Back of ankle/heel', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
(35, 'Rib Fracture', 'Football', 'Chest', 'Side or front of chest', 'Sometimes', 'Sometimes', 'No', 'Yes', 'Sometimes'),
(36, 'Meniscus Tear', 'Football', 'Knee', 'Inside or outside of knee', 'Yes', 'Sometimes', 'Sometimes', 'Yes', 'Sometimes'), 
(37, 'Ankle Sprain', 'Soccer', 'Ankle', 'Outside of ankle', 'Yes', 'Yes', 'Yes', 'Yes', 'Sometimes'),
(38, 'Achilles Tendonitis', 'Soccer', 'Achilles Tendon', 'Back of Ankle', 'Sometimes', 'No', 'No', 'Sometimes', 'No'),
(39, 'Achilles Tendon Rupture', 'Soccer', 'Calf', 'Lower calf', 'Yes', 'Sometimes', 'Yes', 'Yes', 'Yes'),
(40, 'ACL Tear', 'Soccer', 'Knee', 'Deep inside of knee', 'Yes', 'Sometimes', 'Yes', 'Yes', 'Yes'),
(41, 'MCL Tear', 'Soccer', 'Knee', 'Inner side of knee', 'Yes', 'Sometimes', 'Yes', 'Sometimes', 'Sometimes'),
(42, 'Concussion', 'Soccer', 'Head', 'Head', 'No', 'No', 'Sometimes', 'No', 'No'),
(43, 'Groin Strain', 'Soccer', 'Groin', 'Groin, can radiate outward to pelvic area', 'Sometimes', 'Sometimes', 'No', 'Sometimes', 'Sometimes'),
(44, 'Hamstring Strain', 'Soccer', 'Thigh', 'Back of thigh', 'Sometimes', 'Sometimes', 'No', 'Yes', 'Sometimes'),
(45, 'Shin Splint', 'Soccer', 'Shin', 'Front of shin', 'No', 'No', 'No', 'No', 'No'),
(46, 'Turf Toe', 'Soccer', 'Big Toe', 'Base of big toe', 'Yes', 'Sometimes', 'Sometimes', 'Yes', 'Sometimes'),
(47, 'Calf Strain', 'Soccer', 'Calf', 'Back of lower leg', 'Sometimes', 'Sometimes', 'No', 'Yes', 'Sometimes'),
(48, 'Shoulder Dislocation', 'Soccer', 'Shoulder', 'Outer shoulder/deltoid area', 'Yes', 'No', 'Yes', 'Yes', 'Yes');

INSERT INTO INJURY_SEVERITY (severity_id, severity, frequency, recovery_time_avg, can_continue_playing, injury_id) VALUES
('1Mi', 'Mild', 1.47, 2, 'Yes', 1),
('1Mo', 'Moderate', 1.47, 4, 'No', 1),
('1Se', 'Severe', 1.47, 12, 'No', 1),
('2Se', 'Severe', 0.07, 52, 'No', 2),
('3Mo', 'Moderate', 0.07, 4, 'Yes', 3),
('3Se', 'Severe', 0.07, 16, 'No', 3),
('4Mi', 'Mild', 0.12, 4, 'Yes', 4),
('4Mo', 'Moderate', 0.12, 12, 'Yes', 4),
('5Se', 'Severe', 0.01, 52, 'No', 5),
('6Mi', 'Mild', 0.30, 2, 'Yes', 6),
('6Mo', 'Moderate', 0.30, 4, 'Yes', 6),
('7Mo', 'Moderate', 0.10, 4, 'No', 7),
('7Se', 'Severe', 0.10, 6, 'No', 7),
('8Mi', 'Mild', 0.18, 3, 'No', 8),
('8Mo', 'Moderate', 0.18, 6, 'No', 8),
('9Mi', 'Mild', 0.20, 3, 'Yes', 9),
('9Mo', 'Moderate', 0.20, 6, 'No', 9),
('9Se', 'Severe', 0.20, 12, 'No', 9),
('10Mo', 'Moderate', 0.34, 3, 'No', 10),
('11Mi', 'Mild', 0.15, 1, 'Yes', 11),
('11Mo', 'Moderate', 0.15, 2, 'Yes', 11),
('12Mo', 'Moderate', 0.05, 4, 'No', 12),
('12Se', 'Severe', 0.05, 8, 'No', 12),
('13Mi', 'Mild', 0.15, 2, 'Yes', 13),
('13Mo', 'Moderate', 0.15, 6, 'Yes', 13),
('14Mo', 'Moderate', 0.03, 12, 'No', 14),
('14Se', 'Severe', 0.03, 24, 'No', 14),
('15Mi', 'Mild', 0.07, 12, 'No', 15),
('15Mo', 'Moderate', 0.07, 24, 'No', 15),
('16Mo', 'Moderate', 0.04, 52, 'No', 16),
('16Se', 'Severe', 0.04, 78, 'No', 16),
('17Mo', 'Moderate', 0.08, 16, 'No', 17),
('17Se', 'Severe', 0.08, 52, 'No', 17),
('18Mo', 'Moderate', 0.05, 4, 'No', 18),
('19Mi', 'Mild', 0.25, 1, 'Yes', 19),
('19Mo', 'Moderate', 0.25, 3, 'No', 19),
('19Se', 'Severe', 0.25, 6, 'No', 19),
('20Mi', 'Mild', 0.37, 2, 'No', 20),
('20Mo', 'Moderate', 0.37, 4, 'No', 20),
('20Se', 'Severe', 0.37, 12, 'No', 20),
('21Mo', 'Moderate', 0.09, 3, 'No', 21),
('22Mi', 'Mild', 0.20, 1, 'Yes', 22),
('22Mo', 'Moderate', 0.20, 2, 'Yes', 22),
('23Mo', 'Moderate', 0.05, 4, 'No', 23),
('23Se', 'Severe', 0.05, 8, 'No', 23),
('24Mi', 'Mild', 0.03, 2, 'Yes', 24),
('24Mo', 'Moderate', 0.03, 4, 'Yes', 24),
('25Mo', 'Moderate', 0.05, 8, 'No', 25),
('25Se', 'Severe', 0.05, 24, 'No', 25),
('26Mi', 'Mild', 0.10, 3, 'Yes', 26),
('26Mo', 'Moderate', 0.10, 8, 'No', 26),
('26Se', 'Severe', 0.10, 16, 'No', 26),
('27Se', 'Severe', 0.07, 52, 'No', 27),
('28Mo', 'Moderate', 0.70, 2, 'No', 28),
('29Mi', 'Mild', 0.64, 1, 'No', 29),
('29Mo', 'Moderate', 0.64, 6, 'No', 29),
('30Mi', 'Mild', 0.44, 2, 'No', 30),
('30Mo', 'Moderate', 0.44, 4, 'No', 30),
('30Se', 'Severe', 0.44, 8, 'No', 30),
('31Mi', 'Mild', 0.20, 3, 'Yes', 31),
('31Mo', 'Moderate', 0.20, 8, 'No', 31),
('32Mo', 'Moderate', 0.15, 4, 'No', 32),
('32Se', 'Severe', 0.15, 12, 'No', 32),
('33Mi', 'Mild', 0.06, 2, 'Yes', 33),
('33Mo', 'Moderate', 0.06, 4, 'No', 33),
('34Se', 'Severe', 0.05, 52, 'No', 34),
('35Mo', 'Moderate', 0.10, 6, 'No', 35),
('36Mo', 'Moderate', 0.10, 6, 'No', 36),
('36Se', 'Severe', 0.10, 12, 'No', 36),
('37Mi', 'Mild', 0.78, 3, 'Yes', 37),
('38Mo', 'Moderate', 0.05, 9, 'Yes', 38),
('39Se', 'Severe', 0.01, 39, 'No', 39),
('40Se', 'Severe', 0.10, 52, 'No', 40),
('41Mo', 'Moderate', 0.08, 6, 'No', 41),
('42Mo', 'Moderate', 0.44, 2, 'No', 42),
('43Mo', 'Moderate', 0.45, 4, 'No', 43),
('44Mi', 'Mild', 0.60, 3, 'Yes', 44),
('45Mo', 'Moderate', 0.20, 4, 'No', 45),
('46Mo', 'Moderate', 0.04, 4, 'No', 46),
('47Mo', 'Moderate', 0.25, 4, 'No', 47),
('48Mo', 'Moderate', 0.15, 4, 'No', 48),
('48Se', 'Severe', 0.15, 12, 'No', 48);


INSERT INTO MOVE (move_id, move_name, move_description) VALUES
(1, 'Driving to the Basket', 'Dribble-drive toward the hoop, often with a defender in pursuit'),
(2, 'Jump Shot (shooting motion)', 'Repetitive jumping and shooting mechanics'),
(3, 'Landing from a Jump', 'Coming down from a rebound, layup, or shot attempt'),
(4, 'Cutting/Changing Direction', 'Crossovers, defensive slides, and sudden direction changes'),
(5, 'Boxing Out/Post-Up', 'Physical positioning and contact battling for space'),
(6, 'Blocking or Contesting a Shot', "Reaching to alter or block an opponent's shot"),
(7, 'Diving for a Loose Ball / Falling', 'Diving on the floor or falling from contact'),
(8, 'Fast Break Sprint', 'Explosive full-speed running in transition'),
(9, 'Pitching', 'Full overhead throwing motion (wind-up through follow-through)'),
(10, 'Batting/Swing', 'Rotational swing to hit a pitched ball'),
(11, 'Base Running', 'Sprinting between bases'),
(12, 'Sliding', 'Feet-first or head-first slide into a base'),
(13, 'Fielding a Ground Ball', 'Bending/lateral movement to field, followed by a throw'),
(14, 'Catching/Blocking (catcher)', 'Repetitive squatting, blocking, framing'),
(15, 'Diving/Collision', 'Diving for a catch or colliding with wall/player'),
(16, 'Hit By Pitch', 'Direct ball contact with batter/catcher'),
(17, 'Tackling / Collision', 'Direct physical contact with another player involving forceful impact between the body or limbs'),
(18, 'Sudden Cutting', 'Rapidly changing direction while running, placing high stress on the knees, ankles, and other lower-extremity joints'),
(19, 'Explosive Sprinting', 'Rapidly accelerating from a stationary or slow position, requiring sudden, powerful contraction of the leg muscles'),
(20, 'Absorbing Contact', 'Bracing for and receiving physical impact from another player or external force while maintaining balance and body position'),
(21, 'Landing After Jump', 'Returning to the ground after jumping, requiring controlled absorption of body weight and impact through the ankles, knees, and hips'),
(22, 'Running/Sprinting', 'High-speed movement to chase the ball or create space'),
(23, 'Passing', 'Striking the ball to a teammate with control and accuracy'),
(24, 'Kicking/Shooting', 'Forceful strike on the ball, usually aimed at goal'),
(25, 'Dribbling', 'Close ball control while moving past defenders'),
(26, 'Receiving/Trapping', 'Controlling an incoming ball with foot, chest, or thigh'),
(27, 'Heading', 'Using the head to pass, clear, or score'),
(28, 'Jumping/Landing', 'Vertical leap (often for headers) with controlled landing'),
(29, 'Sliding Tackle', 'Sliding on the ground to dispossess an opponent'),
(30, 'Goalkeeper Save/Dive', 'Diving or reaching to stop the ball from entering the goal');


INSERT INTO MOVE_INJURY (move_id, injury_id) VALUES
(1, 2),
(1, 1),
(2, 4),
(2, 9),
(3, 1),
(3, 2),
(4, 2),
(4, 8),
(5, 9),
(5, 6),
(5, 7),
(6, 6),
(6, 7),
(6, 11),
(6, 12),
(7, 11),
(7, 12),
(7, 10),
(8, 8),
(8, 5),
(9, 16),
(9, 13),
(9, 14),
(10, 18),
(10, 17),
(11, 19),
(11, 20),
(12, 20),
(12, 22),
(12, 23),
(13, 19),
(13, 24),
(13, 25),
(14, 24),
(14, 25),
(14, 21),
(15, 21),
(15, 20),
(16, 22),
(16, 23),
(16, 21),
(17, 28),
(17, 32),
(18, 27),
(18, 29),
(19, 30),
(19, 34),
(20, 31),
(20, 35),
(21, 29),
(21, 36),
(22, 44),
(22, 47),
(23, 44),
(23, 43),
(24, 44),
(24, 43),
(25, 37),
(25, 40),
(26, 37),
(26, 41),
(27, 42),
(27, 37),
(28, 37),
(28, 40),
(29, 41),
(29, 37),
(30, 48),
(30, 37),
(30, 40);